services:
  parse-dmarc:
    build: .
    image: ghcr.io/meysam81/parse-dmarc:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_PATH: /data/parse-dmarc.db
    volumes:
      - ./config.json:/app/config.json
      - ./data:/data
