---
services:
  parse-dmarc:
    build: .
    image: ${IMAGE_NAME:-meysam81/parse-dmarc}
    environment:
      DATABASE_PATH: /data/parse-dmarc.db
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
      - parse-dmarc:/data

volumes:
  parse-dmarc:
