apiVersion: 1
providers:
  - name: "parse-dmarc"
    orgId: 1
    folder: "Parse DMARC"
    type: file
    disableDeletion: false
    editable: true
    options:
      path: /var/lib/grafana/dashboards/parse-dmarc
